#!/usr/bin/env python3
"""Merge translated page images into a PDF."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image, ImageOps


IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".tif", ".tiff"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image-dir", required=True, type=Path, help="Directory containing translated page images")
    parser.add_argument("--out", required=True, type=Path, help="Output PDF path")
    parser.add_argument("--manifest", type=Path, help="Manifest generated by prepare_pdf_pages.py")
    parser.add_argument("--dpi", type=int, default=200, help="PDF image resolution")
    parser.add_argument(
        "--fit",
        choices=("stretch", "contain"),
        default="stretch",
        help="How to normalize images to manifest page dimensions",
    )
    return parser.parse_args()


def load_manifest_pages(path: Path | None) -> list[dict]:
    if not path:
        return []
    payload = json.loads(path.expanduser().resolve().read_text(encoding="utf-8"))
    return payload.get("pages", [])


def collect_images(image_dir: Path, manifest_pages: list[dict]) -> list[tuple[Path, tuple[int, int] | None]]:
    image_dir = image_dir.expanduser().resolve()
    if not image_dir.exists():
        raise SystemExit(f"Image directory not found: {image_dir}")

    if manifest_pages:
        images = []
        for page in manifest_pages:
            expected = image_dir / f"page-{int(page['page_number']):03d}.png"
            if not expected.exists():
                matches = sorted(image_dir.glob(f"page-{int(page['page_number']):03d}.*"))
                matches = [path for path in matches if path.suffix.lower() in IMAGE_EXTENSIONS]
                if not matches:
                    raise SystemExit(f"Missing translated image for page {page['page_number']}: {expected}")
                expected = matches[0]
            target = (int(page["render_width_px"]), int(page["render_height_px"]))
            images.append((expected, target))
        return images

    files = sorted(path for path in image_dir.iterdir() if path.suffix.lower() in IMAGE_EXTENSIONS)
    if not files:
        raise SystemExit(f"No image files found in {image_dir}")
    return [(path, None) for path in files]


def normalize_image(path: Path, target: tuple[int, int] | None, fit: str) -> Image.Image:
    image = Image.open(path)
    image = ImageOps.exif_transpose(image).convert("RGB")
    if not target or image.size == target:
        return image
    if fit == "stretch":
        return image.resize(target, Image.Resampling.LANCZOS)

    canvas = Image.new("RGB", target, "white")
    fitted = ImageOps.contain(image, target, Image.Resampling.LANCZOS)
    offset = ((target[0] - fitted.width) // 2, (target[1] - fitted.height) // 2)
    canvas.paste(fitted, offset)
    return canvas


def main() -> int:
    args = parse_args()
    if args.dpi < 72:
        raise SystemExit("--dpi must be at least 72")

    manifest_pages = load_manifest_pages(args.manifest)
    image_specs = collect_images(args.image_dir, manifest_pages)
    pages = [normalize_image(path, target, args.fit) for path, target in image_specs]
    if not pages:
        raise SystemExit("No pages to merge")

    out_path = args.out.expanduser().resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    first, rest = pages[0], pages[1:]
    first.save(out_path, "PDF", resolution=args.dpi, save_all=True, append_images=rest)
    print(f"Merged {len(pages)} page image(s) into {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
