#!/usr/bin/env python3
"""Audit a translated PDF image package."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", required=True, type=Path, help="Manifest generated by prepare_pdf_pages.py")
    parser.add_argument("--translated-dir", required=True, type=Path, help="Directory containing translated page images")
    parser.add_argument("--pdf", type=Path, help="Output PDF to check")
    parser.add_argument("--dimension-tolerance-px", type=int, default=8)
    return parser.parse_args()


def pdf_page_count(path: Path) -> int | None:
    try:
        from pypdf import PdfReader  # type: ignore
    except Exception:
        return None
    return len(PdfReader(str(path)).pages)


def main() -> int:
    args = parse_args()
    manifest_path = args.manifest.expanduser().resolve()
    translated_dir = args.translated_dir.expanduser().resolve()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    pages = manifest.get("pages", [])
    errors: list[str] = []
    warnings: list[str] = []

    if not translated_dir.exists():
        errors.append(f"Translated image directory missing: {translated_dir}")
    else:
        for page in pages:
            page_number = int(page["page_number"])
            image_path = translated_dir / f"page-{page_number:03d}.png"
            if not image_path.exists():
                matches = sorted(translated_dir.glob(f"page-{page_number:03d}.*"))
                if not matches:
                    errors.append(f"Missing translated image for page {page_number}")
                    continue
                image_path = matches[0]
            with Image.open(image_path) as image:
                expected = (int(page["render_width_px"]), int(page["render_height_px"]))
                actual = image.size
                if (
                    abs(actual[0] - expected[0]) > args.dimension_tolerance_px
                    or abs(actual[1] - expected[1]) > args.dimension_tolerance_px
                ):
                    warnings.append(f"Page {page_number} image dimensions {actual} differ from expected {expected}")

    pdf_count = None
    if args.pdf:
        pdf_path = args.pdf.expanduser().resolve()
        if not pdf_path.exists():
            errors.append(f"Output PDF missing: {pdf_path}")
        else:
            pdf_count = pdf_page_count(pdf_path)
            if pdf_count is not None and pdf_count != len(pages):
                errors.append(f"Output PDF has {pdf_count} pages; expected {len(pages)}")
            elif pdf_count is None:
                warnings.append("Could not verify PDF page count because pypdf is unavailable")

    result = {
        "ok": not errors,
        "prepared_page_count": len(pages),
        "pdf_page_count": pdf_count,
        "errors": errors,
        "warnings": warnings,
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if not errors else 1


if __name__ == "__main__":
    sys.exit(main())
