#!/usr/bin/env python3
"""Normalize whole-page generated images to the source PDF render dimensions."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image, ImageOps


IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".tif", ".tiff"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image-dir", required=True, type=Path, help="Directory containing raw imagegen page images")
    parser.add_argument("--manifest", required=True, type=Path, help="Manifest generated by prepare_pdf_pages.py")
    parser.add_argument("--out-dir", required=True, type=Path, help="Directory for normalized page images")
    parser.add_argument(
        "--fit",
        choices=("stretch", "contain"),
        default="stretch",
        help="stretch preserves full-bleed page coverage; contain preserves generated aspect ratio on white canvas",
    )
    return parser.parse_args()


def load_manifest_pages(path: Path) -> list[dict]:
    payload = json.loads(path.expanduser().resolve().read_text(encoding="utf-8"))
    pages = payload.get("pages", [])
    if not pages:
        raise SystemExit(f"No pages found in manifest: {path}")
    return pages


def find_page_image(image_dir: Path, page_number: int) -> Path:
    expected = image_dir / f"page-{page_number:03d}.png"
    if expected.exists():
        return expected

    matches = sorted(image_dir.glob(f"page-{page_number:03d}.*"))
    matches = [path for path in matches if path.suffix.lower() in IMAGE_EXTENSIONS]
    if not matches:
        raise SystemExit(f"Missing generated image for page {page_number}: {expected}")
    return matches[0]


def normalize(image: Image.Image, target: tuple[int, int], fit: str) -> Image.Image:
    image = ImageOps.exif_transpose(image).convert("RGB")
    if image.size == target:
        return image

    if fit == "stretch":
        return image.resize(target, Image.Resampling.LANCZOS)

    canvas = Image.new("RGB", target, "white")
    fitted = ImageOps.contain(image, target, Image.Resampling.LANCZOS)
    offset = ((target[0] - fitted.width) // 2, (target[1] - fitted.height) // 2)
    canvas.paste(fitted, offset)
    return canvas


def main() -> int:
    args = parse_args()
    image_dir = args.image_dir.expanduser().resolve()
    out_dir = args.out_dir.expanduser().resolve()
    if not image_dir.exists():
        raise SystemExit(f"Image directory not found: {image_dir}")

    out_dir.mkdir(parents=True, exist_ok=True)
    pages = load_manifest_pages(args.manifest)
    for page in pages:
        page_number = int(page["page_number"])
        source = find_page_image(image_dir, page_number)
        target = (int(page["render_width_px"]), int(page["render_height_px"]))
        image = Image.open(source)
        normalized = normalize(image, target, args.fit)
        out_path = out_dir / f"page-{page_number:03d}.png"
        normalized.save(out_path, optimize=True)
        print(f"Wrote {out_path} from {source.name}: {image.size} -> {target}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
